version: '3'
services:
  composer:
    image: composer:2.2
    user: "1001:1001"
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - ./app:/app
    restart: never

  phpunit:
    image: php:8.0-fpm-alpine3.14
    user: "1001:1001"
    restart: never
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  php:
    image: php:8.0-fpm-alpine3.14
    volumes:
      - ./app:/app
    working_dir: /app

  web:
    image: nginx:1.21.6-alpine
    ports:
      - 9080:80
    volumes:
      - ./app:/app
      - ./app/var/log/nginx:/var/log/nginx
      - ./app/.conf/nginx/site.conf:/etc/nginx/conf.d/default.conf