#!/bin/bash
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
docker-compose -f $SCRIPTPATH/docker-compose.yml run php --version &&
docker-compose -f $SCRIPTPATH/docker-compose.yml run composer --version &&
docker-compose -f $SCRIPTPATH/docker-compose.yml run composer install &&
docker-compose -f $SCRIPTPATH/docker-compose.yml run composer dumpautoload &&
docker-compose -f $SCRIPTPATH/docker-compose.yml run web nginx --v

